2022-06-08 22:42:16,670 INFO autoreload Watching for file changes with StatReloader
2022-06-08 22:42:40,733 WARNING log Not Found: /adm
2022-06-08 22:42:47,944 WARNING log Not Found: /sdda
2022-06-08 22:43:27,428 WARNING log Not Found: /admin/sadas
2022-06-08 22:45:33,304 WARNING log Forbidden (Permission denied): /posts/add/
Traceback (most recent call last):
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
2022-06-08 22:45:37,822 WARNING log Forbidden (Permission denied): /posts/delete/40
Traceback (most recent call last):
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
  File "C:\Users\outlink\PycharmProjects\HomeWorks\D6_v1\venv\lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
